POST http://localhost:5002/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY1MWJkZGRjY2I2MzVlZDhhZmVmMDlhYyIsImlhdCI6MTY5NjM0MzYyNn0.37Au9YT1pmI2GcVNRSAiKeLZ2L9dQIIS0WXQEgxK22Q

{
    "title": "My First Vlog",
    "author": "Johny Doe",
    "url": "http://www.miccrosoft.com",
    "likes": 10
}